"""add language column to comment table

Revision ID: 46c39f1a0a02
Revises: ef9ad58ae930
Create Date: 2024-06-30 14:50:58.562414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c39f1a0a02'
down_revision = 'ef9ad58ae930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
