"""Add emotion and emotion_score columns

Revision ID: ef9ad58ae930
Revises: 
Create Date: 2024-06-30 11:03:49.799281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9ad58ae930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emotion_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('emotion_score')
        batch_op.drop_column('emotion')

    # ### end Alembic commands ###
